from discord.ext import commands
import discord
import random 

class topic(commands.Cog):
  def __init__(self,client):
    self.client = client

  @commands.command()
  async def truth(self,ctx,*,question):
    """.truth brings back a question"""
    question = ['What is lying in your fridge at the moment?',
                'Would you prefer fries or ceaser salad right now?',
                'How often do you eat salad as a full meal?',
                'If you had 30 secs of everyone’s attention, what is the one thing you will say?',
                'What would you do to quickly get someone’s attention?',
                'I am a person who thinks a lot, what about you?',
                'If you had 30 secs of everyone’s attention, what is the one thing you will say?',
                'What would you do to quickly get someone’s attention?',
                'I am a person who thinks a lot, what about you?',
                'If you had 30 secs of everyone’s attention, what is the one thing you will say?',
                'What would you do to quickly get someone’s attention?',
                'I am a person who thinks a lot, what about you?',
                'What is your wildest fantasy?',
                'Do you ever hit nostalgia and if yes, how do you feel?',
                'Which is the one superpower you wish you had?',
                'Did you always want to be in the profession you are in?',
                'Which is the biggest fear of your life?',
                'Is there anything you would try that you never tried before?',
                'Have you ever planned a conspiracy to stalk someone?',
                'Would you rather chose to be alone and alive or with a group of people and die?',
                'Have you ever been chased by police?',
                'Why are you acting weird for the past few days?',
                'I heard you have a big secret to tell your partner, is that true?',
                'What will you prefer? To be buried or cremated?',
                'Which one do you want to know- When will you die or how will you die?',
                'What is the weather like?',
                'Watch Star Wars or Star Trek? Harry Potter or The Lord of the Rings? Use whichever movies you find most relevant.',
                'Read on a Kindle or paperback book? This question is a starter for many possible conversations on reading, favorite books, technology, libraries, bookstores and more!',
                'Go to a play or musical?',
                'Go to the theater or a movie?',
                'Wear jeans or chinos?',
                'Have a Margarita or Pina Colada?',
                'Drink a glass of Guinness or Fat Tire?',
                'Drink coffee or beer?',
                'Crash with friends or stay in a hotel?',
                'Visit Europe or Mexico?',
                'Vacation in Hawaii or Alaska, and why?',
                'Choose a free trip or money? This may tell you whether the person values experiences over dollars.',
                'Stay in a hotel or an Airbnb home?',
                'Go skiing or snowboading?',
                'Travel by plane, train, or automobile?',
                'Enjoy a houseboat or speed boat?',
                'Go climbing or zip lining?',
                'Hike or bike?',
                'Go to a comedy club or dance club?',
                'Have a night out or evening in?',
                'Watch TV or read a book?',
                'Go canoeing or waterskiing?',
                'Camp in an RV or stay in a tent?',
                'Use Facebook or Twitter?',
                'Use iPhone or Android phone?'
                'Win the lottery or find your perfect job?',
                'Swim in a pool or the ocean? Salt water and waves crashing on the beach or temperature controlled, lovely water all year round.',
                'Travel by sailboat or cruise ship?',
                'Watch sports or play sports?',
                'Play dodgeball or kickball?',
                'When was the last time you lied?',
                'When was the last time you cried?',
                'What is your biggest fear?',
                'Whats your biggest fantasy?',
                'Have you ever masturbated',
                'Do you have any fetishes?',
                'Whats something youre glad your mum doesnt know about you?',
                'Have you ever cheated on someone?',
                'Whats the worst thing youve ever done?',
                'Whats a secret youve never told anyone?',
                'Do you have a hidden talent?',
                'Who was your first celebrity crush?'
                'What are your thoughts on polyamory?'
                'Whats the worst intimate experience youve ever had?',
                'Have you ever cheated in an exam?',
                'Whats the most drunk youve ever been?'
                'Have you ever broken the law?',
                'Whats the most embarrassing thing youve ever done?',
                'Whats your biggest insecurity?',
                'Have you ever stayed friends with someone because it benefitted you beyond just the friendship?',
                'Whats the biggest mistake youve ever made?',
                'Whats the most disgusting thing youve ever done?',
                'Who would you like to kiss in this room?',
                'Whats the worst thing anyones ever done to you?',
                'Have you ever had a run in with the law?',
                'Whats your worst habit?',
                'Whats the worst thing youve ever said to anyone?',
                'Have you ever peed in the shower?',
                'Whats the strangest dream youve had?',
                'Have you ever been caught doing something you shouldnt have?',
                'Whats the worst date youve been on?',
                'Whats your biggest regret?',
                'Whats the biggest misconception about you?',
                'Have you ever said something you regret about someone in this room?','Whats one thing you wish people knew about you?',
                'Wheres the weirdest place youve had sex?',
                'Why did your last relationship break down?',
                'Have you ever lied to get out of a bad date?',
                'Whats the most trouble youve been in?',
                'Whats the worst thing youve ever lied about?',
                'Whats the best piece of advice youve ever been given?',
                'Whats your guilty pleasure?',
                'Whats one thing you only do when youre alone?',
                'If you had to get back with an ex, who would you choose?',
                'If you had to cut one friend out of your life, who would it be?',
                'Do you have a favourite friend?',
                'If you wanted to make out with your guy/girl on campus, where would you do it?',
                'Have you ever gotten into a fistfight on school grounds?',
                'Have you ever fallen asleep while a class was on?',
                'Have you ever been suspended or gotten detention? Why?',
                'If you had the chance, would you sneak a peek in the other gender locker room?',
                'Who is the hottest teacher in school/college?',
                'Have you ever sexted someone you shouldnt?',
                'Have you ever been publicly humiliated? Explain what happened.',
                'What was the strangest dream you had?',
                'Which celebrity would you like to swap lives with for a month?',
                'Which feature do you get complimented on the most? Do you like it?',
                'Name one thing that you would never do even if you were offered all the money in the world.',
                'Among all the people in the room, which boy would you agree to date?',
                'Among all the people in the room, which boy would you never date?',
                'What is that one characteristic or quality that you would like to change about you?',
                'Have you ever fallen out of love? Did you break up after that?',
                'What is the craziest thing that has happened to you in a public place?',
                'Describe the most annoying experience you had at a mall.',
                'What is the meanest thing you have said to someone?',
                'Have you ever considered cheating on your boyfriend?',
                'Have you ever lied to your boyfriend, saying that you feel sick, to avoid an intimate moment?',
                'What is a rumor or gossip you repeated about someone but found out was incorrect?',
                'Are second rounds exciting or exhausting?',
                'Do you fake orgasm while looking sideways or looking the person straight in the face?',
                'Do you have an I’m getting laid tonight outfit? What it is?',
                'Do you have any spicy pictures or videos saved on your phone?',
                'Have you ever been attracted to the same sex?',
                'Have you ever cheated/wanted to cheat?',
                'Have you ever done it in a car?',
                'Have you ever sexted anyone? If so, read one of the sexts in a fake British accent.',
                'How many people have you slept with?',
                'How often do you watch something naughty?',
                'If you got to have a threesome with people in this room, who would you do it with and why?',
                'If you were into the same sex, which celebrity would you go for?',
                'Its totally illegal to seduce my teachers but if it were,…..',
                'What is the most sexually adventurous thing youd want someone to do to you?',
                'What is the most youve done for sex in the past?',
                'What is the song that you get it on to the most?',
                'What panties are you wearing?',
                'What was the most embarrassing time you got turned on?',
                'What would be more thrilling: angry sex or make-up sex?',
                'Whats the most number of times youve done it in one day?',
                'Whats your favorite body part on a girl?',
                'Whats your favorite fantasy to pleasure yourself to?''When did you lose your virginity?',
                'When was a time you were so turned on you couldn’t stand it?',
                'When was the first time you came?',
                'When was your first kiss?',
                'When was your sexual awakening?',
                'Where are you on the straight/queer spectrum?',
                'Who do you most want to sleep with, out of everyone here?',
                'Who was your best partner and why?',
                'Have you ever walked in on your parents in a compromising position?',
                'Have you ever dropped a piece of food, then picked it up off the ground and ate it?',
                'Have you ever tasted your booger?',
                'What is that something that people think you would never do, but you actually have?',
                'Did you ever have an encounter with a police officer?',
                'What is a silly thing you are emotionally attached to?',
                'Name the strangest place you have peed.',
                'Have you ever crapped in your pants after growing up?',
                'What was the most embarrassing thing your parents have caught you doing?',
                'Why did you break up with your last partner?',
                'What is the grossest thing that your partner does?',
                'Name a terrible thing you have done that you lied to cover up.',
                'Did you love someone who didnt love you back?',
                'What is something that you have never told anyone?',
                'What was the most disgusting practical joke you ever played on someone?',
                'What do you think that your boyfriends thoughts are about marriage and kids?',
                'Describe your wildest fantasy.',
                'Have you ever peed in a pool? If yes, was it a private or a public pool?',
                'What was the stupidest thing you have done in front of a crowd?',
                'What is the first thing you would do if you got invisible?',
                'Have you ever been hit on by someone of the same sex? If yes, what happened? How did you react?',
                'Which of the people in this room have the most sensual and daring sense of style?',
                'If you were marooned on a deserted island with one person, who would you like it to be?',
                'What is the stupidest thing you have said to your partner while being intimate?',
                'Have you ever picked your nose absent-mindedly and then eaten it?',
                'Who in this room has the hottest body?',
                'What is your deepest, darkest fear?',
                'Describe your first kiss.',
                'Who is the sexiest person in this room?',
                'What is your biggest regret in life?',
                'Who has the nicest butt in this room?',
                'Name the last person you licked.',
                'Have you ever been cheated on or cheated someone?',
                'Have you ever made out with someone in this room?',
                'What are the things you are self-conscious about?',
                'When was the last time you peed in your bed? What age?',
                'What is the biggest lie you have ever told? Who did you tell it to?',
                'Name a person you regret kissing.',
                'Tell us about an embarrassing vomit story.',
                'What is the naughtiest thing you have done in public? With whom?',
                'What is that one thing most people think is true about you, but isn’t?',
                'What is the naughtiest thing you have gotten away with?',
                'What is a childish thing you still do?',
                'Have you ever let someone else take the blame for something you have done?',
                'Name 10 body parts that your boyfriend likes to kiss.',
                'Name 10 items you bought but regretted buying and never used.',
                'If you were a boy/girl (of the opposite sex), would you make out with yourself?',
                'Describe the most embarrassing moment of your life.',
                'Have you ever stuck chewing gum under a desk?',
                'Which one do you think is better – tests or essays?',
                'Have you ever eaten a meal by yourself? Where and why?',
                'If you had to go to one class for the rest of your life, what class would you choose it to be?',
                'Would you rather lose your sex organs or gain a hundred kilos?',
                'Would you choose to save a persons life without anyone knowing about it or not actually save him but have everyone praise you for it?',
                'If you could only listen to one single song for the rest of your life, which one would it be?',
                'Who in this group would be the worst one to date? Why?',
                'Would you rather live with no AC and heating or no internet?',
                'If someone offered you $1 crore to break up with your boyfriend or girlfriend, would you do it?',
                'Has anyone ever walked in on you when you were peeing or pooping in the toilet?',
                'Would you rather go for a day without wearing a bra or a month without washing your hair?',
                'Have you ever experienced a wardrobe malfunction?',
                'Have you ever absent-mindedly walked into a wall?',
                'Do you ever pick your nose?',
                'Do you sing or dance in the shower?',
                'Have you ever peed yourself while laughing?',
                'Have you ever farted loudly in public?',
                'Do you ever talk to yourself?',
                'You are in a public restroom and just peed. Then, you notice your stall has no water/ toilet paper. What would you do?',
                'What is that one thing in your web history that you would be embarrassed about if someone saw it?','Have you ever tried to take a hot and sexy picture of yourself, but failed?',
                'Do you sleep with a stuffed toy?',
                'Do you ever drool in your sleep?',
                'Do you talk while sleeping?',
                'Do you think [ABC] is cute?',
                'Who do you like the least in this group, and why? (Drama!!)',
                'What would your dream partner look like?',
                'What is your preferred song for the shower?',
                'Who is the hottest person in this room?',
                'Have you ever played board games with your parents?',
                'Have you ever farted in an elevator?',
                'You have a crush on [ABC]. True or false?',
                'Of all the people in this world, who do you want to trade your life with?',
                'What are the things you think about while sitting on the toilet?',
                'Did you have an ‘imaginary’ buddy while growing up?',
                'Did you ever cover your eyes during a gory part in a movie?',
                'Have you ever practiced kissing while looking in a mirror?',
                'Did your parents ever try to give you “the talk”?',
                'Name your most annoying worst habit.',
                'Describe the most disgusting habit you have.',
                'What videos and pictures of you exist that you wish didn’t?',
                'What was the cruelest practical joke you played on a friend?',
                'What is the most embarrassing post you have put up on Facebook or Instagram?',
                'Describe one bad thing you have done that no one else knows about.',
                'Describe the most awkward romantic encounter you have ever had.',
                'What is the grossest food item you have put in your mouth?',
                'Tell us the most embarrassing nickname you have ever had.',
                'Describe your most recent lust/love encounter in detail.',
                'What is the stupidest thing you have done for a boy?',
                'When was the last time you picked your nose?',
                'What is one thing you really hope your parents never find out about you?',
                'Tell us something you don’t want anyone to know.',
                'Describe one thing you have done that people present here would judge you for doing?',
                'What was the last thing you searched for on Google?',
                'If you had to choose between going naked everywhere for a week or having your thoughts appear in bubbles above your head, which one would you choose and why?']           
    await ctx.send(f'Question: {random.choice(question)}')

def setup(client):
  client.add_cog(topic(client))